# The container images used in this Nix configuration repository.

[[containers]]
repository = "docker.gitea.com"
name = "gitea"
tag = "1-rootless"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.gitea.com"
name = "act_runner"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.n8n.io"
name = "n8nio/n8n"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "louislam/uptime-kuma"
tag = "1"
architectures = ["linux/amd64"]
[[containers]]
repository = "ghcr.io"
name = "onedr0p/exportarr"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "msroest/sabnzbd_exporter"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "solarkennedy/ipmi-kvm-docker"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "jellyfin/jellyfin"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "ghcr.io"
name = "monstermuffin/mergerfs-cache-mover"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "glanceapp/glance"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "ghcr.io"
name = "linuxserver/sabnzbd"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "ghcr.io"
name = "linuxserver/radarr"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "ghcr.io"
name = "linuxserver/sonarr"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "fallenbagel/jellyseerr"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "quay.io"
name = "minio/minio"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "sonarqube"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "postgres"
tag = "17"
architectures = ["linux/amd64"]
[[containers]]
repository = "ghcr.io"
name = "fred-drake/gitea-check-service"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "lscr.io"
name = "linuxserver/kavita"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "ghcr.io"
name = "linuxserver/calibre"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "ghcr.io"
name = "linuxserver/calibre-web"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "lscr.io"
name = "linuxserver/lazylibrarian"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "library/redis"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "ghcr.io"
name = "paperless-ngx/paperless-ngx"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "apache/tika"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "gotenberg/gotenberg"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "clusterzx/paperless-ai"
tag = "latest"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "woodpeckerci/woodpecker-server"
tag = "v3"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "woodpeckerci/woodpecker-agent"
tag = "v3"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "postgres"
tag = "18"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "postgres"
tag = "16-alpine"
architectures = ["linux/amd64"]
[[containers]]
repository = "ghcr.io"
name = "browserless/chromium"
tag = "v2.18.0"
architectures = ["linux/amd64"]
[[containers]]
repository = "docker.io"
name = "amruthpillai/reactive-resume"
tag = "latest"
architectures = ["linux/amd64"]

